# ベースイメージとしてPostgreSQLの最新バージョンを使用
FROM postgres:latest

# 必要なパッケージのインストール
RUN apt-get update && apt-get install -y \
    postgresql-server-dev-all \
    gcc \
    git \
    make \
    && rm -rf /var/lib/apt/lists/*

# pgvectorのインストール
RUN cd /tmp && \
    git clone --branch v0.7.2 https://github.com/pgvector/pgvector.git && \
    cd pgvector && \
    make && \
    make install

# データディレクトリをボリュームとして設定
VOLUME ["/var/lib/postgresql/data"]
